# conveniently convert gene alias into valid gene symbol
- based on org.Xx.eg.db
- get official gene symbol from 
  - a string of a list of gene alias/symbol with comma/space or any other non letter/number/- charactor.
  - gene alias
  - if not matched, give it a or some recommended gene, or report it
- one step to replace/insert gene vector
- list all mostly used gene ids 
  - ENTREZID, HGNC/MGI, ENSEMBL, SYMBOL, official name, alias
- Export all gene info into a local html 
  - R create shortcut?
- homologous gene
  - eg. map mouse genes into human genes
  - export a html/table for search
- collapse a gene vector into a un/quoted string
  - write it into clipboard so as to paste it wherever
